name: cert-manager-config

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4.2.0

      - name: Login into registry ghcr.io
        run: echo  ${{ secrets.GITHUB_TOKEN }} | helm registry login --username ${{ github.actor }} ghcr.io --password-stdin

      - name: Package and publish Helm chart
        run: |-
          helm package --version ${{ github.ref_name }} --app-version ${{ github.ref_name }} cert-manager-config
          helm push cert-manager-config-${{ github.ref_name }}.tgz oci://ghcr.io/tenzin-io

  devel:
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4.2.0

      - name: Login into registry ghcr.io
        run: echo  ${{ secrets.GITHUB_TOKEN }} | helm registry login --username ${{ github.actor }} ghcr.io --password-stdin

      - name: Package and publish Helm chart
        run: |-
          helm package --version v0.0.0 --app-version v0.0.0 cert-manager-config
          helm push cert-manager-config-v0.0.0.tgz oci://ghcr.io/tenzin-io
