name: ingress-external

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  PACKAGE_NAME: ingress-external

jobs:
  release:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4.2.0

      - name: Login into registry ghcr.io
        run: echo  ${{ secrets.GITHUB_TOKEN }} | helm registry login --username ${{ github.actor }} ghcr.io --password-stdin

      - name: Package and publish Helm chart
        run: |-
          helm package --version ${{ github.ref_name }} --app-version ${{ github.ref_name }} ${{ env.PACKAGE_NAME }}
          helm push ${{ env.PACKAGE_NAME }}-${{ github.ref_name }}.tgz oci://ghcr.io/tenzin-io

  devel:
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4.2.0

      - name: Login into registry ghcr.io
        run: echo  ${{ secrets.GITHUB_TOKEN }} | helm registry login --username ${{ github.actor }} ghcr.io --password-stdin

      - name: Package and publish Helm chart
        run: |-
          helm package --version v0.0.0 --app-version v0.0.0 ${{ env.PACKAGE_NAME }}
          helm push ${{ env.PACKAGE_NAME }}-v0.0.0.tgz oci://ghcr.io/tenzin-io
